lightroom_web/config/routes.rb
LightroomWeb::Application.routes.draw do
  resources :images

end

lightroom_web/app/models/image.rb
class Image
  require Rails.root.join("lib/datamapper_cocoatime")
  include DataMapper::Resource

  storage_names[:default] = "Adobe_images"
  
  property :id, Serial, :field => "id_local"
  property :global_id, UUID, :field => "id_global"
  property :pick, Integer, :field => "pick"
  property :rating, Integer, :field => "rating"
  property :touchtime, CocoaTime, :field => "touchtime"
  property :capturetime, DateTime, :field => "capturetime"
  has n, :image_keywords
  has n, :keywords, :through => :image_keywords
  before :save do
     self.touchtime = Time.now
  end
  


end

lightroom_web/app/models/image_keyword.rb
class ImageKeyword

  include DataMapper::Resource

  storage_names[:default] = "AgLibraryKeywordImage"
  property :id, Serial, :field => "id_local"
  property :image_id, Integer, :field => "image"
  property :keyword_id, Integer, :field => "tag"
  belongs_to :image
  belongs_to :keyword

end

lightroom_web/app/models/keyword.rb
class Keyword

  include DataMapper::Resource
  storage_names[:default] = "AgLibraryKeyword"
  property :id, Serial, :field => "id_local"
  property :name, String #, :field => "name"
  has n, :image_keywords

end

lightroom_web/app/controllers/application_controller.rb
require 'dm-rails/middleware/identity_map'
class ApplicationController < ActionController::Base
  use Rails::DataMapper::Middleware::IdentityMap
  protect_from_forgery
end

lightroom_web/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.xml
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @images }
    end
  end

  # GET /images/1
  # GET /images/1.xml
  def show
    @image = Image.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/new
  # GET /images/new.xml
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.get(params[:id])
  end

  # POST /images
  # POST /images.xml
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to(@image, :notice => 'Image was successfully created.') }
        format.xml  { render :xml => @image, :status => :created, :location => @image }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    @image = Image.get(params[:id])

    respond_to do |format|
      if @image.update(params[:image])
        format.html { redirect_to(@image, :notice => 'Image was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = Image.get(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to(images_url) }
      format.xml  { head :ok }
    end
  end
end

lightroom_web/app/helpers/application_helper.rb
module ApplicationHelper
end

lightroom_web/app/helpers/images_helper.rb
module ImagesHelper
end

lightroom_web/app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lightroom_web/app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

lightroom_web/app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= link_to 'Show', image %></td>
    <td><%= link_to 'Edit', edit_image_path(image) %></td>
    <td><%= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Image', new_image_path %>

lightroom_web/app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

lightroom_web/app/views/images/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

lightroom_web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LightroomWeb</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>